name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
      - name: Run UI tests
        working-directory: ui-tests
        run: mvn -q -DskipTests=false test -DsuiteXmlFile=src/test/resources/testng.xml
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Newman
        run: npm install -g newman
      - name: Run API tests
        working-directory: api-tests/postman
        run: newman run finance-credit-union.postman_collection.json -e environments/local.postman_environment.json --reporters cli,html --reporter-html-export newman-report.html
